import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// 1. Setup __dirname equivalent for ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 2. Load the plugin's package.json
const pkgPath = path.join(__dirname, '../package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

// 3. Automatically find the iOS source directory
// Capacitor standard structure: ios/Sources/<PluginName>
const sourcesDir = path.join(__dirname, '../ios/Sources');

if (!fs.existsSync(sourcesDir)) {
  console.warn('⚠️  [CapKit] ios/Sources directory not found. Skipping Version.swift generation.');
  process.exit(0);
}

const pluginFolderName = fs.readdirSync(sourcesDir).find((f) => fs.statSync(path.join(sourcesDir, f)).isDirectory());

if (!pluginFolderName) {
  console.error('❌ [CapKit] Could not find a source directory in ios/Sources');
  process.exit(1);
}

const versionFilePath = path.join(sourcesDir, pluginFolderName, 'Version.swift');
const webVersionFilePath = path.join(__dirname, '../src/version.ts');

const content = `// This file is automatically generated. Do not modify manually.
import Foundation

/**
  Container for the plugin's version information.
  This enum provides a centralized, single source of truth for the native 
  version string, synchronized directly from the project's 'package.json'.
  It ensures parity across JavaScript, Android, and iOS platforms.
 */
public enum PluginVersion {
    /**
      The semantic version string of the plugin.
      Value synchronized from package.json: "${pkg.version}"
     */
    public static let number = "${pkg.version}"
}
`;

try {
  fs.writeFileSync(versionFilePath, content);
  console.log(`✅ [CapKit] Version.swift updated to v${pkg.version} in ${pluginFolderName}`);
} catch (err) {
  console.error('❌ [CapKit] Error generating Version.swift:', err);
  process.exit(1);
}

const webVersionContent = `// This file is automatically generated. Do not modify manually.
export const PLUGIN_VERSION = '${pkg.version}';
`;

try {
  fs.writeFileSync(webVersionFilePath, webVersionContent);
  console.log(`✅ [CapKit] src/version.ts updated to v${pkg.version}`);
} catch (err) {
  console.error('❌ [CapKit] Error generating src/version.ts:', err);
  process.exit(1);
}
