#!/usr/bin/env tsx
/**
 * @file prepare-demo.ts
 * Copy the demo app into a plugin's example-app/ and apply its patches.
 *
 * Usage (from plugin dir):
 *   tsx ../../scripts/prepare-demo.ts
 *
 * Or from monorepo root:
 *   tsx scripts/prepare-demo.ts <plugin>
 */
import { execSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, relative, resolve } from "node:path";

// --- Config ---
const ROOT = resolve(import.meta.dirname, "..");
const DEMO = join(ROOT, "demo");

const EXCLUDE = new Set([
  "node_modules",
  ".git",
  ".angular",
  ".turbo",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
]);

// --- Helpers ---
const log = (emoji: string, msg: string) => console.log(`${emoji} ${msg}`);
const die = (msg: string): never => {
  console.error(`❌ ${msg}`);
  process.exit(1);
};

function copyDir(src: string, dest: string) {
  mkdirSync(dest, { recursive: true });
  for (const e of readdirSync(src, { withFileTypes: true })) {
    if (EXCLUDE.has(e.name)) continue;
    const s = join(src, e.name);
    const d = join(dest, e.name);
    if (e.isDirectory()) {
      copyDir(s, d);
    } else {
      writeFileSync(d, readFileSync(s));
    }
  }
}

function findPatches(dir: string): string[] {
  const result: string[] = [];
  if (!existsSync(dir)) return result;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      result.push(...findPatches(p));
    } else if (e.name.endsWith(".patch")) {
      result.push(p);
    }
  }
  return result;
}

/** Copy non-patch files from staticDir into targetDir, preserving structure. */
function copyStaticFiles(staticDir: string, targetDir: string) {
  if (!existsSync(staticDir)) return;

  function walk(dir: string) {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const src = join(dir, e.name);
      if (e.isDirectory()) {
        walk(src);
      } else if (!e.name.endsWith(".patch")) {
        const rel = relative(staticDir, src);
        const dest = join(targetDir, rel);
        mkdirSync(join(dest, ".."), { recursive: true });
        writeFileSync(dest, readFileSync(src));
        log("📄", `Copied: ${rel}`);
      }
    }
  }
  walk(staticDir);
}

function applyPatches(staticDir: string, targetDir: string) {
  const patches = findPatches(staticDir);
  if (!patches.length) {
    log("⏭️", "No patches found");
    return;
  }
  let ok = 0;
  for (const patch of patches) {
    const rel = relative(targetDir, patch);
    try {
      execSync(`patch -p1 -N -V never -i "${patch}"`, {
        cwd: targetDir,
        stdio: "pipe",
      });
      log("✅", `Applied: ${rel}`);
      ok++;
    } catch {
      log("⚠️", `Failed: ${rel}`);
    }
  }
  log("🩹", `Patches: ${ok}/${patches.length}`);

  // Clean up .orig files left by patch (recursive)
  function cleanOrig(dir: string) {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) {
        cleanOrig(p);
      } else if (e.name.endsWith(".orig")) {
        rmSync(p);
      }
    }
  }
  cleanOrig(targetDir);
}

// --- Resolve plugin ---
const cwd = process.cwd();
const args = process.argv.slice(2);
const cleanupOnly = args.includes("--cleanup");
const argPlugin = args.find((a) => !a.startsWith("--"));

// If argPlugin given: ROOT/packages/<argPlugin>/example-app
// If not: assume CWD is the plugin dir → CWD/example-app
const plugin = argPlugin ?? relative(join(ROOT, "packages"), cwd);
const exampleApp = argPlugin
  ? join(ROOT, "packages", plugin, "example-app")
  : join(cwd, "example-app");

if (!existsSync(exampleApp)) die(`Not found: ${exampleApp}`);
if (!existsSync(DEMO)) die(`Demo not found: ${DEMO}`);

const staticDir = join(exampleApp, "static");

// Step 1: Clean example-app (keep static/ and .gitignore)
const KEEP = new Set(["static", ".gitignore"]);
log("🧹", "Cleaning example-app...");
for (const entry of readdirSync(exampleApp)) {
  if (KEEP.has(entry)) continue;
  rmSync(join(exampleApp, entry), { recursive: true, force: true });
}

if (cleanupOnly) {
  log("🧹", `Cleanup done! Kept: ${[...KEEP].join(", ")}`);
  process.exit(0);
}

// Step 2: Copy demo → example-app
log("📦", "Copying demo → example-app...");
copyDir(DEMO, exampleApp);

// Step 3: Apply patches from static/
log("🩹", "Applying patches...");
applyPatches(staticDir, exampleApp);

// Step 4: Copy non-patch files from static/ to example-app
log("📄", "Copying static files...");
copyStaticFiles(staticDir, exampleApp);

// Step 5: Write fixed .gitignore (always the same, not versioned from static/)
writeFileSync(
  join(exampleApp, ".gitignore"),
  "# Generated by prepare-demo.ts — do not edit\n*\n!static/\n!static/**\n",
);
log("📝", "Wrote .gitignore");

log("🎉", `Done! example-app ready for "${plugin}"`);
