// This file is automatically generated. Do not modify manually.
import Foundation

/**
  Container for the plugin's version information.
  This enum provides a centralized, single source of truth for the native 
  version string, synchronized directly from the project's 'package.json'.
  It ensures parity across JavaScript, Android, and iOS platforms.
 */
public enum PluginVersion {
    /**
      The semantic version string of the plugin.
      Value synchronized from package.json: "8.0.0"
     */
    public static let number = "8.0.0"
}
